# Set global variables used throughout the pipeline
variables:
    MAVEN_IMAGE: "maven:3.9.3-amazoncorretto-17"
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

# Define the stages that make up the pipeline
stages:
    - build
    - test

# Configure caching to speed up Maven builds by reusing dependencies
cache:
    paths:
        - .m2/repository

# Stage for building the Maven project
maven_build:
    image: $MAVEN_IMAGE
    stage: build
    script:
        - mvn clean package
    artifacts:
        paths:
            - fintrack-api/target/  # Share the entire target folder

# Stage for running unit tests and generating code coverage report
unit_tests:
    image: $MAVEN_IMAGE
    stage: test
    script:
        - mvn test
    artifacts:
        when: always
        paths:
            - fintrack-api/target/  # Share the entire target folder
        reports:
            junit: fintrack-api/target/surefire-reports/TEST-*.xml

# Stage for converting Jacoco code coverage report to Cobertura format
coverage_report:
    # This stage should be placed after the stage that generates Jacoco coverage report
    stage: test
    needs:
        - unit_tests
    image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
    script:
        # Convert Jacoco report to Cobertura, specifying paths and output location
        - python /opt/cover2cover.py fintrack-api/target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/fintrack-api/src/main/java/ > cobertura.xml
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: cobertura.xml

# Stage for running integration tests on the 'main' branch
integration_tests:
    image: $MAVEN_IMAGE
    stage: test
    services:
        - docker:20.10.16-dind
#    only:
#        - main
    needs:
        - unit_tests
    script:
        - mvn verify -DskipUTs -Dtest.integration.docker.host=$DOCKER_HOST
