@startuml
title Maven CI Workflow Sequence Diagram

actor User as U
participant GitHub as GH
participant "build job" as B
participant "unit-test job" as UT
participant "integration-test job" as IT

== Main branch Push Event ==
U -> GH: Push to main branch
activate GH
GH -> B: Trigger build on push
activate B
B -> GH: Checkout main branch
GH --> B
B -> B : Maven Clean Package
B --> GH:
deactivate B
GH -> UT: Trigger unit-test
activate UT
UT -> UT: test execution
UT --> GH
deactivate UT
GH -> IT: Trigger integration-test
activate IT
IT -> IT: Integration Tests \n in parallel for all modules
IT --> GH
deactivate IT
deactivate GH

== Merge Request Lifecycle ==
U -> GH: Create PR from feature branch
activate GH
GH -> B: Trigger build on push
activate B
B -> GH: Checkout feature branch
GH --> B
B -> B : Maven Clean Package
B --> GH:
deactivate B
GH -> UT: Trigger unit-test
activate UT
UT -> UT: test execution
UT --> GH
deactivate UT
deactivate GH

loop when PR is updated
    U -> GH: Push to feature branch
    activate GH
    GH -> B: Trigger build on push
    activate B
    B -> GH: Checkout feature branch
    GH --> B
    B -> B : Maven Clean Package
    B --> GH:
    deactivate B
    GH -> UT: Trigger unit-test
    activate UT
    UT -> UT: test execution
    UT --> GH
    deactivate UT
    deactivate GH
end

U -> GH: Merge PR
activate GH
GH -> B: Trigger build on push
activate B
B -> GH: Checkout main branch
GH --> B
B -> B : Maven Clean Package
B --> GH:
deactivate B
GH -> UT: Trigger unit-test
activate UT
UT -> UT: test execution
UT --> GH
deactivate UT
GH -> IT: Trigger integration-test
activate IT
IT -> IT: Integration Tests \n in parallel for all modules
IT --> GH
deactivate IT
deactivate GH

@enduml
