spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/fintrack_local
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
    sql:
        init:
            mode: never
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yaml