version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fintrack_local
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    links:
      - database
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@fintrack.yazilim.vip
      PGADMIN_DEFAULT_PASSWORD: admin
      SCRIPT_NAME: /pgadmin