[versions]
spring-boot = "3.3.4"
spring-dependencyManagement = "1.1.6"

[libraries]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "spring-dependencyManagement" }