server:
    servlet:
        context-path: /api
spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/db_local
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
    sql:
        init:
            mode: never
    liquibase:
        enabled: true
        change-log: classpath:liquibase/changelog.xml
        contexts: ${spring.profiles.active}
    docker:
        compose:
            enabled: false
app:
    exceptions-stack-trace: false
