name: Build
on: [push]
jobs:
  build:
    name: Maven Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Update to Java 17
          distribution: 'adopt'
      - name: Execute mvn verify
        run: |
          ./mvnw clean verify -PcodeCoverage
      - name: Upload fintrack-api coverage report
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: Fintrack API report
          path: fintrack-api/target/site/jacoco  # Change this path if your JaCoCo report is generated in a different location