name: Build
on: [push]
jobs:
  build:
    name: Maven Verify
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Update to Java 17
          distribution: 'adopt'
      - name: Start Docker daemon
        run: |
          dockerd &
          # Wait for docker to be up and running
          sleep 10
      - name: Execute mvn verify
        continue-on-error: true
        run: ./mvnw verify -PcodeQuality,codeCoverage,dependencyCheck sonar:sonar