name: Maven CI

on:
    pull_request:
        branches:
            - main

env:
    JAVA_VERSION: 17
    MAVEN_VERSION: 3.8.1  # Adjust if you want a different Maven version

jobs:
    build:
        name: 'Build & Test'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: ${{ env.JAVA_VERSION }}
            - name: Cache Maven packages
              uses: actions/cache@v2
            - name: Maven Clean Package
              run: mvn -B -Ptest clean install
