name: Maven CI

on:
    push:
        branches:
            - '**/*'
    pull_request:
        branches:
            - main

env:
    JAVA_VERSION: 17
    MAVEN_VERSION: 3.8.1  # Adjust if you want a different Maven version
    CACHE_KEY: maven-local-repo

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: ${{ env.JAVA_VERSION }}

            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ env.CACHE_KEY }}-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ env.CACHE_KEY }}-${{ runner.os }}-

            - name: Maven Clean Package
              run: mvn -B clean package -DskipUTs

    unit-test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: ${{ env.JAVA_VERSION }}

            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ env.CACHE_KEY }}-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ env.CACHE_KEY }}-${{ runner.os }}-

            - name: Maven Test
              run: mvn -B test

    integration-test:
        needs: unit-test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        services:
            docker:
                image: docker:20.10.5-dind
                options: --privileged
        strategy:
            matrix:
                module: [fintrack-api]  # Add or remove module names as needed
            fail-fast: false
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: ${{ env.JAVA_VERSION }}

            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ env.CACHE_KEY }}-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ env.CACHE_KEY }}-${{ runner.os }}-

            - name: Maven Verify Integration Test
              run: mvn -B verify -DskipUTs -pl ${{ matrix.module }} -am
