name: (M) infrastructure
on: workflow_dispatch

env:
  REGISTRY: ghcr.io

  # must be exists on deployment server
  BASE_PATH: /root/budget-tracker
  FOLDER_NAME: deployment
jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing Environment
        run: |
          FOLDER_PATH=${{ env.BASE_PATH }}/${{ env.FOLDER_NAME }}
          ARCHIVE="${{ env.FOLDER_NAME }}-$(date '+%Y%m%d%H%M%S').tar.gz"
          echo "FOLDER_PATH=$FOLDER_PATH" >> $GITHUB_ENV
          echo "ARCHIVE=$ARCHIVE" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Creating tarball archive from config files
        run: tar -zcvf ${{ env.ARCHIVE }} ${{ env.FOLDER_NAME }}
      - name: Transferring archive to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BT_SV_HOST }}
          username: ${{ secrets.BT_SV_USERNAME }}
          key: ${{ secrets.BT_SV_PRIVATE_KEY }}
          port: ${{ secrets.BT_SV_PORT }}
          source: ${{ env.ARCHIVE }}
          target: ${{ env.BASE_PATH }}
      - name: Re-initialize infrastructure on the server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.BT_SV_HOST }}
          username: ${{ secrets.BT_SV_USERNAME }}
          key: ${{ secrets.BT_SV_PRIVATE_KEY }}
          port: ${{ secrets.BT_SV_PORT }}
          script: |
            rm -rf ${{ env.FOLDER_PATH }}
            cd ${{ env.BASE_PATH }} && tar -xzvf ${{ env.ARCHIVE }}
            export REGISTRY="${{ env.REGISTRY }}"
            export REGISTRY_USERNAME="${{ github.actor }}"
            export REGISTRY_PASSWORD="${{ secrets.GITHUB_TOKEN }}"
            export FOLDER_PATH="${{ env.FOLDER_PATH }}"
            export MODULES="database proxy backend client"
            ${{ env.FOLDER_PATH }}/scripts/deploy.sh
